name: Generate Contribution Breakout

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate Breakout SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: LizardoFSA
          ball_color: "#bf40bf"
          paddle_color: "#f2e6ff"
          bricks_colors: "#f2e6ff,#e6ccff,#cc99ff,#b366ff,#8000ff"

      - name: Move generated SVG to temp
        run: |
          mkdir -p /tmp/breakout-images
          mv output/custom.svg /tmp/breakout-images/github-contribution-breakout.svg

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and force-push SVG to output branch
        run: |
          git checkout --orphan output
          git rm -rf .
          mv /tmp/breakout-images/*.svg .
          git add *.svg
          git commit -m "chore: update contribution breakout svg" || echo "No changes to commit"
          git push --force origin output
